### ISSUE TITLE
Error en las Actions

### ISSUE THREAD

**Issue by stephaniearismendi** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct09-filesystem-notes-app-stephaniearismendi#1]
Me están dando error las actions porque no me reconoce el módulo fs.

Concretamente, da el error: "**_Cannot find module 'fs' or its corresponding type declarations._**"

**Comment by stephaniearismendi** [comment]
@esegredo

**Comment by esegredo** [comment]
Hola Stephanie,

¿Has instalado el paquete @types/node como dependencia de desarrollo (--save-dev) en tu proyecto?

Saludos.

**Comment by stephaniearismendi** [comment]
> Hola Stephanie,
> 
> ¿Has instalado el paquete @types/node como dependencia de desarrollo (--save-dev) en tu proyecto?
> 
> Saludos.

Creo que no lo había instalado como dependencia de desarrollo. Ya funciona, gracias
